/MODELOS/
INSERT INTO MARCAS (NOME_MARCA)
VALUES('VW');
INSERT INTO MARCAS (NOME_MARCA)
VALUES('TOYOTA');
INSERT INTO MARCAS (NOME_MARCA)
VALUES('GM');

INSERT INTO MODELOS (DESC_MODELO,NOME_MARCA)
VALUES('GOL',  'VW');
INSERT INTO MODELOS (DESC_MODELO,NOME_MARCA)
VALUES('GOLF',  'VW');
INSERT INTO MODELOS (DESC_MODELO,NOME_MARCA)
VALUES('SAVEIRO',  'VW');
INSERT INTO MODELOS (DESC_MODELO,NOME_MARCA)
VALUES('SONIC',  'GM');
INSERT INTO MODELOS (DESC_MODELO,NOME_MARCA)
VALUES('HILUX',  'TOYOTA');



/AUTOMOVEIS/
INSERT INTO AUTOMOVEIS (PLACA,DESC_MODELO,NOME_MARCA,RENAVAM,COR,N_PORTAS,TIPO_COMBUSTIVEL)
VALUES('KLH8H22', 'GOL',  'VW', 12345678991, 'BRANCO', 4, 'GAS');


INSERT INTO AUTOMOVEIS (PLACA,DESC_MODELO,NOME_MARCA,RENAVAM,COR,N_PORTAS,TIPO_COMBUSTIVEL)…
/MODELOS/
INSERT INTO MARCAS (NOME_MARCA)
VALUES('VW');
INSERT INTO MARCAS (NOME_MARCA)
VALUES('TOYOTA');
INSERT INTO MARCAS (NOME_MARCA)
VALUES('GM');

INSERT INTO MODELOS (DESC_MODELO,NOME_MARCA)
VALUES('GOL',  'VW');
INSERT INTO MODELOS (DESC_MODELO,NOME_MARCA)
VALUES('GOLF',  'VW');
INSERT INTO MODELOS (DESC_MODELO,NOME_MARCA)
VALUES('SAVEIRO',  'VW');
INSERT INTO MODELOS (DESC_MODELO,NOME_MARCA)
VALUES('SONIC',  'GM');
INSERT INTO MODELOS (DESC_MODELO,NOME_MARCA)
VALUES('HILUX',  'TOYOTA');



/AUTOMOVEIS/
INSERT INTO AUTOMOVEIS (PLACA,DESC_MODELO,NOME_MARCA,RENAVAM,COR,N_PORTAS,TIPO_COMBUSTIVEL)
VALUES('KLH8H22', 'GOL',  'VW', 12345678991, 'BRANCO', 4, 'GAS');
INSERT INTO AUTOMOVEIS (PLACA,DESC_MODELO,NOME_MARCA,RENAVAM,COR,N_PORTAS,TIPO_COMBUSTIVEL)
VALUES('KLE6H23', 'GOLF',  'VW', 12345678912, 'ROSA', 4, 'GASOLINA');
INSERT INTO AUTOMOVEIS (PLACA,DESC_MODELO,NOME_MARCA,RENAVAM,COR,N_PORTAS,TIPO_COMBUSTIVEL)
VALUES('KLE6H44', 'SAVEIRO',  'VW', 12345678914, 'PRATA', 4, 'ALCOOL');
INSERT INTO AUTOMOVEIS (PLACA,DESC_MODELO,NOME_MARCA,RENAVAM,COR,N_PORTAS,TIPO_COMBUSTIVEL)
VALUES('KLE6H61', 'SONIC',  'GM', 12345678916, 'AZUL', 4, 'GASOLINA');
INSERT INTO AUTOMOVEIS (PLACA,DESC_MODELO,NOME_MARCA,RENAVAM,COR,N_PORTAS,TIPO_COMBUSTIVEL)
VALUES('KLE6H29', 'HILUX',  'TOYOTA', 12345678917, 'PRETO', 4, 'DIESEL');



INSERT INTO CLIENTES (CPF,NOME,ENDERECO,TELEFONE) 
VALUES(11111111111, 'CARLOS ANTONIO',  'RUA JARDIM BOTANICO', 27999999999);
INSERT INTO CLIENTES (CPF,NOME,ENDERECO,TELEFONE)
VALUES(22222222223, 'SEU ZE',  'RUA JARDINS', 27111111111);
INSERT INTO CLIENTES (CPF,NOME,ENDERECO,TELEFONE)
VALUES(11111111114, 'PEDRO',  'RUA PRIMULA', 27222222222);
INSERT INTO CLIENTES (CPF,NOME,ENDERECO,TELEFONE)
VALUES(11111111115, 'CARLOS',  'RUA AUGUSTA', 27333333333);

INSERT INTO LOCACACOES(DESC_MODELO,NOME_MARCA,PLACA,CPF,DATA_LOCACAO,DATA_DEVOLUCAO) 
VALUES('GOL','VW','KLH8H22',11111111111,TO_DATE('01/01/1970', 'DD/MM/YYYY'),TO_DATE('02/01/1970', 'DD/MM/YYYY'));


SELECT * 
FROM AUTOMOVEIS;

SELECT *
FROM LOCACOES;


SELECT *
FROM MARCAS;

SELECT *
FROM MODELOS;

SELECT *
FROM CLIENTES;
COMMIT;